ALTER TABLE enrollments 
ADD COLUMN IF NOT EXISTS birth_place TEXT,
ADD COLUMN IF NOT EXISTS nationality TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS last_diploma TEXT,
ADD COLUMN IF NOT EXISTS motivation TEXT;