// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://magoeegjfwxkvnrgaxhx.supabase.co";
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ29lZWdqZnd4a3ZucmdheGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDQ5MTgsImV4cCI6MjA1MDYyMDkxOH0.RHU2V05kS8K5hkZvhw2YIUbR2snlQRAMQK20eqq4KnY";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
