// This file is automatically generated. Do not edit it directly.

// Définition temporaire du type Database car database.types.ts est vide
export interface Database {
  public: {
    Tables: {
      formations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          title: string;
          description: string;
          requirements: string;
          duration: string | null;
          category_id: string | null;
          icon_color: string | null;
          image_url: string | null;
          published: boolean;
          pole: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          title: string;
          description: string;
          requirements: string;
          duration?: string | null;
          category_id?: string | null;
          icon_color?: string | null;
          image_url?: string | null;
          published?: boolean;
          pole?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          title?: string;
          description?: string;
          requirements?: string;
          duration?: string | null;
          category_id?: string | null;
          icon_color?: string | null;
          image_url?: string | null;
          published?: boolean;
          pole?: string | null;
        };
      };
      gallery: {
        Row: {
          id: string;
          created_at: string;
          media_type: string;
          media_url: string;
          title: string | null;
          description: string | null;
          published: boolean;
          order_position: number | null;
          thumbnail_url: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          media_type: string;
          media_url: string;
          title?: string | null;
          description?: string | null;
          published?: boolean;
          order_position?: number | null;
          thumbnail_url?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          media_type?: string;
          media_url?: string;
          title?: string | null;
          description?: string | null;
          published?: boolean;
          order_position?: number | null;
          thumbnail_url?: string | null;
        };
      };
      news: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          title: string;
          slug: string;
          excerpt: string;
          content: string;
          image_url: string | null;
          author: string | null;
          published: boolean;
          published_at: string | null;
          category: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          title: string;
          slug: string;
          excerpt: string;
          content: string;
          image_url?: string | null;
          author?: string | null;
          published?: boolean;
          published_at?: string | null;
          category?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          title?: string;
          slug?: string;
          excerpt?: string;
          content?: string;
          image_url?: string | null;
          author?: string | null;
          published?: boolean;
          published_at?: string | null;
          category?: string | null;
        };
      };
      enrollments: {
        Row: {
          id: string;
          created_at: string;
          student_name: string;
          student_email: string;
          student_phone: string;
          formation_id: string | null;
          status: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          student_name: string;
          student_email: string;
          student_phone: string;
          formation_id?: string | null;
          status?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          student_name?: string;
          student_email?: string;
          student_phone?: string;
          formation_id?: string | null;
          status?: string;
          notes?: string | null;
        };
      };
      payments: {
        Row: {
          id: string;
          created_at: string;
          enrollment_id: string | null;
          amount: number;
          payment_date: string | null;
          payment_method: string | null;
          status: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          enrollment_id?: string | null;
          amount: number;
          payment_date?: string | null;
          payment_method?: string | null;
          status?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          enrollment_id?: string | null;
          amount?: number;
          payment_date?: string | null;
          payment_method?: string | null;
          status?: string;
          notes?: string | null;
        };
      };
      intake_dates: {
        Row: {
          id: string;
          created_at: string;
          formation_id: string | null;
          start_date: string;
          end_date: string | null;
          available_slots: number | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          formation_id?: string | null;
          start_date: string;
          end_date?: string | null;
          available_slots?: number | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          formation_id?: string | null;
          start_date?: string;
          end_date?: string | null;
          available_slots?: number | null;
          notes?: string | null;
        };
      };
      [key: string]: {
        Row: any;
        Insert: any;
        Update: any;
      };
    };
    Enums: {
      [key: string]: string;
    };
    Functions: {
      [key: string]: {
        Args: any;
        Returns: any;
      };
    };
  };
}

// Type helper pour les tables Supabase
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];