// This file is automatically generated. Do not edit it directly.
import type { Database } from "./database.types";

// Type helper pour les tables Supabase
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];